Hw02 express
makfiz/nodejs-hw-rest-api pull request #1
Opened 2023-01-07 20:50 UTC by makfiz

2023-01-07 21:04 UTC, KhYulian commented on models/contacts.js
> +  }
try catch в цих функціях не потрібен

2023-01-07 21:04 UTC, KhYulian commented on models/contacts.js
> +  }
помилки обробляйте в контроллері

2023-01-07 21:05 UTC, KhYulian commented on models/contacts.js
> +      }
для цього є Joi

2023-01-07 21:05 UTC, KhYulian commented on models/contacts.js
> +      }
Валідуєте body в контролері вбо, що краще, в окремій middleware

2023-01-07 21:06 UTC, KhYulian commented on routes/api/contacts.js
> +  const { error } = addContactSchema.validate(req.body);
Здійснюйте валідацію в окремій middleware, яка спрацьовуватиме перед контроллером

2023-01-07 21:06 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-07 21:07 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення :)

2023-01-08 20:02 UTC, makfiz commented on routes/api/contacts.js
> +  const { error } = addContactSchema.validate(req.body);
done

2023-01-08 20:03 UTC, makfiz commented on models/contacts.js
> +      }
done

2023-01-08 20:03 UTC, makfiz commented on models/contacts.js
> +  }
done

2023-01-08 21:06 UTC, KhYulian approved these changes
👌

2023-01-08 21:09 UTC, merged